name: pm2.5-prediction
on: 
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run:
          pip install -r requirements.txt

      - name: Setup GCP Credentials
        env:
          GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}
        run: |
          python - <<'EOF'
          import os, base64
          key_b64 = os.environ["GCP_KEY_JSON"]
          with open("key.json", "wb") as f:
              f.write(base64.b64decode(key_b64))
          EOF
      
      - name: Setup DVC remote credentials
        run: |
          dvc remote modify --local gcp-bucket-1 credentialpath key.json
      
      - name: Pulling dataset from bucket
        run: |
          dvc pull

      - name: Reproducing pipeline
        run: |
          dvc repro

      - name: Fetching main branch metrics
        run: |
          git config --global --add safe.directory /__w/pm2.5-prediction/pm2.5-prediction
          git fetch --prune
      
      - name: Write reports and metrics with CML
        env:
          REPO_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          # Post reports as comments in GitHub PRs
          echo "## Current model performance"
          echo "![](scatterplot_with_prediction.png)" >> report.md

          echo "## Metrics comparison (current branch vs main)"
          dvc metrics diff main --md >> report.md
          cml comment create report.md